// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompanyEmployee.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220505000941_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca761332-ed42-11ce-bacd-00aa0057b223"),
                            Address = "My address",
                            Country = "My Country",
                            Name = "IT_Solutions ltd."
                        },
                        new
                        {
                            Id = new Guid("ca761233-ed42-11ce-bacd-00aa0057b223"),
                            Address = "My 2nd Address",
                            Country = "My country",
                            Name = "Internal Bank ltd"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca761232-ed42-11ce-bacd-00aa0057b323"),
                            Age = 30,
                            CompanyId = new Guid("ca761332-ed42-11ce-bacd-00aa0057b223"),
                            Name = "Mr.Ade",
                            Position = "Software dev."
                        },
                        new
                        {
                            Id = new Guid("ca761232-ed42-11ce-bacd-00aa0057b123"),
                            Age = 25,
                            CompanyId = new Guid("ca761332-ed42-11ce-bacd-00aa0057b223"),
                            Name = "Mr. Adams",
                            Position = "Backend Engineer"
                        },
                        new
                        {
                            Id = new Guid("ca761233-ed42-11ce-bacd-00aa0057b223"),
                            Age = 35,
                            CompanyId = new Guid("ca761233-ed42-11ce-bacd-00aa0057b223"),
                            Name = "Kane Miller",
                            Position = "Administrator"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany("employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
