// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace CompanyEmployee.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Address")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca761332-ed42-11ce-bacd-00aa0057b223"),
                            Address = "My address",
                            Country = "My Country",
                            Name = "IT_Solutions ltd."
                        },
                        new
                        {
                            Id = new Guid("ca761233-ed42-11ce-bacd-00aa0057b223"),
                            Address = "My 2nd Address",
                            Country = "My country",
                            Name = "Internal Bank ltd"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca761232-ed42-11ce-bacd-00aa0057b323"),
                            Age = 30,
                            CompanyId = new Guid("ca761332-ed42-11ce-bacd-00aa0057b223"),
                            Name = "Mr.Ade",
                            Phone = 0,
                            Position = "Software dev."
                        },
                        new
                        {
                            Id = new Guid("ca761232-ed42-11ce-bacd-00aa0057b123"),
                            Age = 25,
                            CompanyId = new Guid("ca761332-ed42-11ce-bacd-00aa0057b223"),
                            Name = "Mr. Adams",
                            Phone = 0,
                            Position = "Backend Engineer"
                        },
                        new
                        {
                            Id = new Guid("ca761233-ed42-11ce-bacd-00aa0057b223"),
                            Age = 35,
                            CompanyId = new Guid("ca761233-ed42-11ce-bacd-00aa0057b223"),
                            Name = "Kane Miller",
                            Phone = 0,
                            Position = "Administrator"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
